export const BID_ERROR_CODES = {
  AUCTION_NOT_LIVE: 'AUCTION_NOT_LIVE',
  BID_TOO_LOW: 'BID_TOO_LOW',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  CAP_REACHED: 'CAP_REACHED',
  AUCTION_ENDED: 'AUCTION_ENDED',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
} as const;

export type BidErrorCode = (typeof BID_ERROR_CODES)[keyof typeof BID_ERROR_CODES];
